### ISSUE TITLE
Regression in 4.4.0: `data` no longer consistently an array and widgets render incorrectly in VIS2 runtime

### ISSUE THREAD

**Issue by Martin-int01** [oweitman/ioBroker.vis-jsontemplate#163]
****Describe the bug****  
Since updating  from **4.3.11** to **4.4.0**, several existing VIS2 JSONTemplate widgets broke in the browser runtime.

There seem to be two regressions:

**1. **Changed `data` structure / incompatible runtime data****
   Templates that previously worked with:

   const entries = data.slice(-500).sort((a, b) => b.ts - a.ts);

started failing in 4.4.0 because data was no longer consistently an array.
In some cases it behaved like an empty object or another structure, causing:

- TypeError: data.slice is not a function
- tables showing only headers but no rows
- intermittent empty states in runtime

**2. Wrong widget rendering in browser runtime**
Widgets that looked correct in the VIS2 editor were rendered incorrectly in the normal browser runtime.
One example was my log widget, which was rendered effectively fullscreen / outside the configured widget bounds instead of staying inside the defined VIS2 widget area.

After downgrading back to 4.3.11, all affected widgets worked again without any template changes.

**To Reproduce**

1. Install or update vis-jsontemplate to 4.4.0
2. Open a VIS2 view containing an existing JSONTemplate widget that renders log data in a table
3. Use a template that expects data to be an array, for example:
const entries = data.slice(-500).sort((a, b) => b.ts - a.ts);
4. Open the view in the normal browser runtime
5. Observe one or more of the following:
- data.slice is not a function
- only table headers are shown, but no rows
- widget content is rendered with wrong size / wrong position
- widget looks correct in the VIS2 editor, but wrong in runtime
6. Downgrade back to 4.3.11
7. Observe that the same widgets work again without changing the template

**Expected behavior**
Version 4.4.0 should remain compatible with widgets that worked in 4.3.11.

- data should still be usable in templates that previously received an array
- widgets should render inside their configured VIS2 bounds
- browser runtime output should match the VIS2 editor
- widgets should not be rendered fullscreen or outside their configured position and size

**Screenshots & Logfiles**
Symptoms observed:

- TypeError: data.slice is not a function
- table headers visible, but no log rows
- widget rendered at wrong size / wrong position in browser runtime
- VIS2 editor looked correct while browser runtime was broken

**Versions:**
- Adapter version: 4.4.0
- JS-Controller version: 7.0.7
- Node version: v22.22.0

**Additional context**
Additional environment details:
- npm: 10.9.4
- ioBroker running on Ubuntu 24.04

Important detail:

- Downgrading from 4.4.0 to 4.3.11 fixes the issue completely on my system.
- No template changes were needed after the downgrade.
- One earlier visible regression in 4.4.0 was the log widget being rendered effectively fullscreen instead of within the configured widget area.
- Another recurring issue was that data no longer behaved like an array in runtime.

**Comment by oweitman** [comment]
Okay, I tested both versions with a single data point containing only a simple array.

```
[
12,
19,
3,
5,
2,
3
]
```

My template is also simple:

```
<%
debugger;
data.slice();
%>
```

To test, I opened the browser console, so that inserting a space in the template retriggers the rendering process and the debugger stops at the debugger command.

` ... The code looks like this (this is the rendered result of the template):

<img width="482" height="379" alt="Image" src="https://github.com/user-attachments/assets/4b631a71-eff4-4c4f-b72e-f235f6961622" />

And the scope (i.e., the current state of the variables) looks like this:

<img width="434" height="262" alt="Image" src="https://github.com/user-attachments/assets/d9730f42-8f9d-4e6a-9d64-c6a59e8cba49" />

In both versions, the data arrives in `data` as an array. 
Further execution of `data.slice();` produced no errors.

Please provide me with your template (ideally a simplified version), as well as corresponding test data in the data point (or something on how I can create the test data myself; you mentioned log data), so that I can reproduce the issue myself.

The error message "TypeError: data.slice is not a function" could mean that your data is either not arriving in `data` at all, and `data` is then null or a different data type, such as an array. `slice` is only available for the array type.

if you prefer to wirte in german, that is no problem

**Comment by Martin-int01** [comment]
Hi oweitman,

gerne auch auf deutsch :-)
Vielen Dank für dein Feedback!

**Zu Punkt 1:**
Das konnte ich nun fixen. Das Problem war in meiner Vorlage. Nun bekomme ich sauber die Daten. 
`  const entries = rows
    .slice(-500)
    .sort((a, b) => (b.ts || 0) - (a.ts || 0));`

**Zu Punkt 2:**
Leider wird das Widget in der Browser Runtime immer noch falsch gerendert. Dies passiert nur in der Version 4.4.0.
Es handelt sich hier um ein Bewässerungslog welches vom logparser Adapter generiert wird. Ich hab dir mal das Json und die Vorlage angehängt.

Vielen Dank im Voraus

lg

[logparser.0.visualization.table3.json.json](https://github.com/user-attachments/files/26667065/logparser.0.visualization.table3.json.json)

[vorlage.txt](https://github.com/user-attachments/files/26667069/vorlage.txt)

**Comment by oweitman** [comment]
Mit Version 4.4.1 sollte das behoben sein.
Die styles kamen mit der letzten Version nicht mehr mit (sieht man oben auch, das style: undefined ist)
Aus dem Grund hat dein template bei manchen css Einstellungen den Fallback gewählt.
Daher kam dann die abweichende Darstellung.
Bitte mal probieren und hier zurückmelden ob es klappt

**Comment by Martin-int01** [comment]
Hallo,

habe soeben 4.4.1 getestet. Leider klappt es immer noch nicht. Nun wird das Widget in der browser runtime nicht mehr in vollbildschirm angezeigt, sondern oben links. Weiters ist mir aufgefallen, dass andere widgets gar nicht mehr angezeigt werden. Ich hab dir mal die Vorlage des anderen Widgets beigefügt.

[Vorlage_Alexa_Logs.txt](https://github.com/user-attachments/files/26683050/Vorlage_Alexa_Logs.txt)

**Comment by oweitman** [comment]
und nun die v4.4.2
nochmal eine Zeile hinzugefügt, die irgendwie verloren gegangen ist.

**Comment by Martin-int01** [comment]
Hallo,

funktioniert nun perfekt!

Vielen vielen Dank!!!

**Comment by oweitman** [comment]
Super
